### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by davesbell** [0liv1er/omci-wireshark-dissector#6]
Running Wireshark Version 4.4.0 with Lua 5.4.6.

Loading this plugin gives me the following error:

```
Multiple problems found

Lua: Error during loading:
/Users/dave.bell/.config/wireshark/plugins/BinDecHex.lua:53: attempt to call a nil value (global 'module')
stack traceback:
/Users/dave.bell/.config/wireshark/plugins/BinDecHex.lua:53: in main chunk
[C]: in function 'require'

Lua: Error during loading:
/Users/dave.bell/.config/wireshark/plugins/BinDecHex.lua:53: attempt to call a nil value (global 'module')
stack traceback:
/Users/dave.bell/.config/wireshark/plugins/BinDecHex.lua:53: in main chunk
[C]: in function 'require'
/Users/dave.bell/.config/wireshark/plugins/omci.lua:43: in main chunk
[C]: in function 'require'
```

I've no idea what this means :)

**Comment by icyfireorb** [comment]
I encountered same error.  All I can do is get my wireshark back to 4.2.7, and I can have omci plugins working correctly.

**Comment by 0liv1er** [comment]
The error is cause by the BinDecHex dependency because of lua 5.4 API change.
I removed the file in the branch [remove-bindechex-dependency](https://github.com/0liv1er/omci-wireshark-dissector/tree/remove-bindechex-dependency).
As I don't have access to Wireshark 4.4.0, please test it and give feedback. Thanks.

**Comment by davesbell** [comment]
This works great! Thanks

**Comment by 0liv1er** [comment]
Merge to master
